### ISSUE TITLE
kvdo compile fails on debiant (kernel 4.9)

### ISSUE THREAD

**Issue by doppelgrau** [dm-vdo/kvdo#10]
There seems so be some API Change (e.g. https://gitlab.com/cip-project/cip-kernel/linux-cip/commit/1eff9d322a444245c67515edb52bc0eb68374aa8 ) so kvdo does not compile on current kernel without some changes (like in https://github.com/akiradeveloper/dm-writeboost/issues/164)

  CC [M]  /usr/local/src/kvdo-master/vdo/kernel/kernelLayer.o
In file included from /usr/local/src/kvdo-master/vdo/kernel/deadlockQueue.h:27:0,
                 from /usr/local/src/kvdo-master/vdo/kernel/kernelLayer.h:37,
                 from /usr/local/src/kvdo-master/vdo/kernel/kernelLayer.c:22:
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘clearBioOperationAndFlags’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:88:6: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   bio->bi_rw = 0;
      ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘copyBioOperationAndFlags’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:98:5: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   to->bi_rw = from->bi_rw;
     ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h:98:19: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   to->bi_rw = from->bi_rw;
                   ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘setBioOperationFlag’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:108:6: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   bio->bi_rw |= flag;
      ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘clearBioOperationFlag’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:118:6: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   bio->bi_rw &= ~flag;
      ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘isDiscardBio’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:181:32: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   return (bio != NULL) && ((bio->bi_rw & REQ_DISCARD) != 0);
                                ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h:181:42: error: ‘REQ_DISCARD’ undeclared (first use in this function)
   return (bio != NULL) && ((bio->bi_rw & REQ_DISCARD) != 0);
                                          ^~~~~~~~~~~
/usr/local/src/kvdo-master/vdo/kernel/bio.h:181:42: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘isFlushBio’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:193:14: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   return (bio->bi_rw & REQ_FLUSH) != 0;
              ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h:193:24: error: ‘REQ_FLUSH’ undeclared (first use in this function)
   return (bio->bi_rw & REQ_FLUSH) != 0;
                        ^~~~~~~~~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘isFUABio’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:205:14: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   return (bio->bi_rw & REQ_FUA) != 0;
              ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘isEmptyFlush’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:227:14: error: ‘BIO {aka struct bio}’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
   return (bio->bi_rw & REQ_FLUSH) != 0;
              ^~
/usr/local/src/kvdo-master/vdo/kernel/bio.h:227:24: error: ‘REQ_FLUSH’ undeclared (first use in this function)
   return (bio->bi_rw & REQ_FLUSH) != 0;
                        ^~~~~~~~~
In file included from /usr/local/src/kvdo-master/vdo/kernel/deadlockQueue.h:27:0,
                 from /usr/local/src/kvdo-master/vdo/kernel/kernelLayer.h:37,
                 from /usr/local/src/kvdo-master/vdo/kernel/kernelLayer.c:22:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:229:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/usr/local/src/kvdo-master/vdo/kernel/bio.h: In function ‘isDiscardBio’:
/usr/local/src/kvdo-master/vdo/kernel/bio.h:183:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
/usr/src/linux-headers-4.9.0-6-common/scripts/Makefile.build:298: die Regel für Ziel „/usr/local/src/kvdo-master/vdo/kernel/kernelLayer.o“ scheiterte

**Comment by tomasz-grobelny** [comment]
Use this patch as workaround.
[compile_vdo_on_debian.patch.log](https://github.com/dm-vdo/kvdo/files/2037601/compile_vdo_on_debian.patch.log)

**Comment by doppelgrau** [comment]
With that patch it compiles, but doesn't work.
Tried to create an vdo-volume but it allwys throws some error and if I try to use the device, it creates IO-errors.

e.g. ./vdo create  --vdoLogicalSize=8T  --sparseIndex=enabled -n=vdo1   --device=/dev/sdb


[  156.588411] uds: loading out-of-tree module taints kernel.
[  156.592941] uds: modprobe: 
[  156.592943] loaded version 6.2.0.19

[  156.797033] kvdo: modprobe: 
[  156.797035] loaded version 6.2.0.35

[  157.308907] kvdo0:dmsetup: 
[  157.308908] starting device 'vdo0'

[  157.308930] kvdo0:dmsetup: 
[  157.308931] underlying device, REQ_FLUSH: supported, REQ_FUA: not supported

[  157.308934] kvdo0:dmsetup: 
[  157.308935] Using write policy async automatically.

[  157.308955] kvdo0:dmsetup: 
[  157.308957] zones: 1 logical, 1 physical, 1 hash; base threads: 5

[  157.427201] kvdo0:dmsetup: 
[  157.427203] Setting UDS index target state to online

[  157.427219] kvdo0:dmsetup: 
[  157.427220] device 'vdo0' started

[  157.427338] uds: kvdo0:dedupeQ: 
[  157.427341] creating index: dev=/dev/disk/by-id/ata-SAMSUNG_MZ7LM960HMJP-00005_S2TZNX0J403263 offset=4096 size=23847940096

[  157.427424] kvdo0:dmsetup: 
[  157.427426] resuming device 'vdo0'

[  157.427429] kvdo0:dmsetup: 
[  157.427431] device 'vdo0' resumed

[  157.427771] uds: kvdo0:dedupeQ: 
[  157.427772] Using 8 indexing zones for concurrency.

[  157.428494] uds: kvdo0:dedupeQ: 
[  157.428494] verifyBufferedData got unexpected data
[  157.428495] : UDS Error: Corrupt saved component (1030)

[  157.428501] uds: kvdo0:dedupeQ: 
[  157.428502] index_0: could not allocate index
[  157.428502] : UDS Error: Corrupt saved component (1030)

[  157.431381] uds: kvdo0:dedupeQ: 
[  157.431382] failed to create index
[  157.431382] : UDS Error: Corrupt saved component (1030)

[  157.431384] uds: kvdo0:dedupeQ: 
[  157.431384] Failed to make router
[  157.431385] : UDS Error: Corrupt saved component (1030)

[  157.431391] uds: kvdo0:dedupeQ: 
[  157.431391] Failed creating index
[  157.431391] : UDS Error: Corrupt saved component (1030)

[  157.431410] kvdo0:dedupeQ: 
[  157.431412] Error creating index dev=/dev/disk/by-id/ata-SAMSUNG_MZ7LM960HMJP-00005_S2TZNX0J403263 offset=4096 size=23847940096
[  157.431413] : UDS Error: Corrupt file (1030)

[  157.431416] kvdo0:dedupeQ: 
[  157.431417] Setting UDS index target state to error

[  157.456963] kvdo0:packerQ: 
[  157.456965] compression is enabled

[  198.272017] uds: kvdo0:journalQ: 
[  198.272018] assertion "
[  198.272021] DataVIOs released from recovery journal in order. Recovery journal point is (1, 0), but commit waiter point is (0, 1)
[  198.272024] " (beforeJournalPoint(&journal->commitPoint, &dataVIO->recoveryJournalPoint)) failed at /usr/local/src/kvdo-master/vdo/base/recoveryJournal.c:1078

[  198.272026] uds: kvdo0:journalQ: 
[  198.272027] [backtrace]

[  198.272032] CPU: 4 PID: 1877 Comm: kvdo0:journalQ Tainted: G           O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  198.272034] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  198.272036]  0000000000000000 ffffffff8df2f774 ffff9e9a1c2b3860 ffffc0c5c21c7d40
[  198.272042]  ffffffffc0b53109 ffff9e9a00000030 ffffc0c5c21c7d60 ffffc0c5c21c7d10
[  198.272046]  3fe820db7f367c18 ffffffff8dce5494 00000000000126c0 ffffc0c5c21c7da0
[  198.272051] Call Trace:
[  198.272059]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  198.272080]  [<ffffffffc0b53109>] ? assertionFailedLogOnly+0x49/0x70 [uds]
[  198.272086]  [<ffffffff8dce5494>] ? lock_timer_base+0x74/0x90
[  198.272115]  [<ffffffffc0ba11c1>] ? continueCommittedWaiter+0x91/0x130 [kvdo]
[  198.272135]  [<ffffffffc0ba1130>] ? continueWaiter+0x70/0x70 [kvdo]
[  198.272158]  [<ffffffffc0b9779f>] ? notifyNextWaiter+0x3f/0x70 [kvdo]
[  198.272179]  [<ffffffffc0b97834>] ? notifyAllWaiters+0x64/0x90 [kvdo]
[  198.272198]  [<ffffffffc0ba2300>] ? completeWrite+0xd0/0x630 [kvdo]
[  198.272219]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  198.272224]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  198.272242]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  198.272246]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  198.272250]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  198.272254]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  198.272300] uds: kvdo0:physQ0: 
[  198.272301] assertion "
[  198.272304] recovery journal point is monotonically increasing, recovery point: 0.1, block recovery point: 1.0
[  198.272306] " (beforeJournalPoint(&journal->recoveryPoint, recoveryPoint)) failed at /usr/local/src/kvdo-master/vdo/base/slabJournal.c:870

[  198.272309] uds: kvdo0:physQ0: 
[  198.272310] [backtrace]

[  198.272315] CPU: 1 PID: 1880 Comm: kvdo0:physQ0 Tainted: G           O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  198.272316] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  198.272318]  0000000000000000 ffffffff8df2f774 0000000000010408 ffffc0c5c2407d20
[  198.272324]  ffffffffc0b5309f ffff9e9a00000030 ffffc0c5c2407d48 ffffc0c5c2407ce8
[  198.272328]  92bcfe4cae4fd8a0 92bcfe4cae4fd8a0 ffff9e9a2f21e000 ffff9e9a3fc58980
[  198.272332] Call Trace:
[  198.272340]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  198.272361]  [<ffffffffc0b5309f>] ? assertionFailed+0x4f/0x70 [uds]
[  198.272391]  [<ffffffffc0b90c90>] ? addEntry+0x70/0x170 [kvdo]
[  198.272413]  [<ffffffffc0b90f67>] ? addEntryFromWaiter+0x1d7/0x2a0 [kvdo]
[  198.272418]  [<ffffffff8e210edf>] ? schedule_timeout+0x16f/0x380
[  198.272444]  [<ffffffffc0b9779f>] ? notifyNextWaiter+0x3f/0x70 [kvdo]
[  198.272464]  [<ffffffffc0b901fa>] ? addEntries.part.8+0xda/0x280 [kvdo]
[  198.272488]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  198.272492]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  198.272513]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  198.272517]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  198.272521]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  198.272524]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  198.272565] kvdo0:journalQ: 
[  198.272566] Unrecoverable error, entering read-only mode
[  198.272568] : UDS Internal Error: Assertion failed (66568)

[  250.709120] kvdo0:dmsetup: 
[  250.709122] suspending device 'vdo0'

[  250.709160] ------------[ cut here ]------------
[  250.709178] WARNING: CPU: 2 PID: 2314 at /build/linux-6WgLIg/linux-4.9.88/drivers/scsi/scsi_lib.c:1034 scsi_init_io+0x142/0x1e0 [scsi_mod]
[  250.709179] Modules linked in: kvdo(O) uds(O) dm_mod cfg80211 rfkill 8021q garp mrp stp llc bonding intel_rapl sb_edac edac_core x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm ast ttm irqbypass joydev crct10dif_pclmul crc32_pclmul ghash_clmulni_intel evdev drm_kms_helper iTCO_wdt iTCO_vendor_support intel_cstate intel_uncore drm lpc_ich pcspkr wmi i2c_algo_bit intel_rapl_perf mfd_core sg ipmi_si ipmi_msghandler mei_me ioatdma acpi_power_meter button acpi_pad mei shpchp parport_pc ppdev lp parport ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto ecb mbcache hid_generic usbhid hid btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod sd_mod crc32c_intel aesni_intel aes_x86_64 glue_helper
[  250.709263]  lrw gf128mul ablk_helper cryptd ahci libahci xhci_pci ehci_pci libata i2c_i801 ehci_hcd xhci_hcd i2c_smbus usbcore scsi_mod usb_common ixgbe dca ptp pps_core mdio
[  250.709287] CPU: 2 PID: 2314 Comm: dmsetup Tainted: G           O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  250.709289] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  250.709291]  0000000000000000 ffffffff8df2f774 0000000000000000 0000000000000000
[  250.709296]  ffffffff8dc78a5e ffff9e9a2a335a10 ffff9e9a2a335a10 00000000ffffffea
[  250.709300]  0000000000000000 ffff9e9a2972a800 0000000000000000 ffffffffc0368da2
[  250.709305] Call Trace:
[  250.709314]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  250.709322]  [<ffffffff8dc78a5e>] ? __warn+0xbe/0xe0
[  250.709333]  [<ffffffffc0368da2>] ? scsi_init_io+0x142/0x1e0 [scsi_mod]
[  250.709340]  [<ffffffffc03ec9ab>] ? sd_init_command+0x2ab/0xda0 [sd_mod]
[  250.709348]  [<ffffffffc0360cb4>] ? scsi_host_alloc_command+0x44/0xb0 [scsi_mod]
[  250.709359]  [<ffffffffc0369109>] ? scsi_prep_fn+0xe9/0x170 [scsi_mod]
[  250.709364]  [<ffffffff8df0366b>] ? blk_peek_request+0x17b/0x2b0
[  250.709375]  [<ffffffffc036a7ad>] ? scsi_request_fn+0x3d/0x5e0 [scsi_mod]
[  250.709381]  [<ffffffff8dc2f200>] ? recalibrate_cpu_khz+0x10/0x10
[  250.709384]  [<ffffffff8defea45>] ? __blk_run_queue+0x35/0x40
[  250.709388]  [<ffffffff8df2a49e>] ? cfq_insert_request+0x2ae/0x530
[  250.709393]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  250.709404]  [<ffffffffc0b1c740>] ? dev_suspend+0x220/0x220 [dm_mod]
[  250.709408]  [<ffffffff8df03ead>] ? blk_queue_bio+0x3bd/0x3d0
[  250.709412]  [<ffffffff8df02005>] ? generic_make_request+0x115/0x2d0
[  250.709439]  [<ffffffffc0bab931>] ? synchronousFlush+0x91/0xe0 [kvdo]
[  250.709462]  [<ffffffffc0ba7a99>] ? vdoPostsuspend+0x59/0xb0 [kvdo]
[  250.709471]  [<ffffffffc0b19f15>] ? dm_table_postsuspend_targets+0x45/0x60 [dm_mod]
[  250.709478]  [<ffffffffc0b15ce4>] ? __dm_destroy+0x1f4/0x240 [dm_mod]
[  250.709486]  [<ffffffffc0b1c740>] ? dev_suspend+0x220/0x220 [dm_mod]
[  250.709494]  [<ffffffffc0b1c811>] ? dev_remove+0xd1/0x110 [dm_mod]
[  250.709501]  [<ffffffffc0b1ce00>] ? ctl_ioctl+0x1b0/0x470 [dm_mod]
[  250.709510]  [<ffffffffc0b1d0cf>] ? dm_ctl_ioctl+0xf/0x20 [dm_mod]
[  250.709514]  [<ffffffff8de1b392>] ? do_vfs_ioctl+0xa2/0x620
[  250.709519]  [<ffffffff8de08fad>] ? __fput+0x17d/0x220
[  250.709523]  [<ffffffff8de1b984>] ? SyS_ioctl+0x74/0x80
[  250.709527]  [<ffffffff8dc03b7d>] ? do_syscall_64+0x8d/0xf0
[  250.709531]  [<ffffffff8e21244e>] ? entry_SYSCALL_64_after_swapgs+0x58/0xc6
[  250.709533] ---[ end trace 0917cfbc07998adb ]---
[  250.709536] blk_peek_request: bad return=-22
[  250.709618] kvdo0:dmsetup: 
[  250.709620] device 'vdo0' suspended

[  250.709682] kvdo0:dmsetup: 
[  250.709683] stopping device 'vdo0'

[  250.710151] uds: kvdo0:logQ0: 
[  250.710153] assertion "
[  250.710155] decrement of lock counter must not underflow
[  250.710158] " ((*currentValue >= 1)) failed at /usr/local/src/kvdo-master/vdo/base/lockCounter.c:302

[  250.710162] uds: kvdo0:logQ0: 
[  250.710163] [backtrace]

[  250.710169] CPU: 1 PID: 1879 Comm: kvdo0:logQ0 Tainted: G        W  O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  250.710171] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  250.710173]  0000000000000000 ffffffff8df2f774 ffffc0c5c2cd4000 ffffc0c5c21ebd98
[  250.710181]  ffffffffc0b53109 0000000000000020 ffffc0c5c21ebda8 ffffc0c5c21ebd68
[  250.710186]  2d55839766cf7975 ffffc0c5c21ebda0 ffffc0c5c21ebe08 ffffffff8dce6594
[  250.710192] Call Trace:
[  250.710201]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  250.710229]  [<ffffffffc0b53109>] ? assertionFailedLogOnly+0x49/0x70 [uds]
[  250.710235]  [<ffffffff8dce6594>] ? del_timer_sync+0x44/0x50
[  250.710267]  [<ffffffffc0b83fe4>] ? releaseLockCountReference+0xd4/0x100 [kvdo]
[  250.710299]  [<ffffffffc0b8e002>] ? finishPageWrite+0x52/0x150 [kvdo]
[  250.710330]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  250.710335]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  250.710363]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  250.710369]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  250.710374]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  250.710378]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  250.710383] uds: kvdo0:logQ0: 
[  250.710384] assertion "
[  250.710386] dirty page count underflow for generation 139
[  250.710388] " ((zone->dirtyPageCounts[generation] > 0)) failed at /usr/local/src/kvdo-master/vdo/base/blockMapTree.c:297

[  250.710392] uds: kvdo0:logQ0: 
[  250.710393] [backtrace]

[  250.710398] CPU: 1 PID: 1879 Comm: kvdo0:logQ0 Tainted: G        W  O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  250.710400] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  250.710402]  0000000000000000 ffffffff8df2f774 0000000000010408 ffffc0c5c21ebda8
[  250.710408]  ffffffffc0b5309f ffffc0c500000030 ffffc0c5c21ebdb8 ffffc0c5c21ebd70
[  250.710414]  2d55839766cf7975 ffffc0c5c21ebe08 ffffffff8dce6594 ffff9e9a3fc526c0
[  250.710420] Call Trace:
[  250.710425]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  250.710447]  [<ffffffffc0b5309f>] ? assertionFailed+0x4f/0x70 [uds]
[  250.710453]  [<ffffffff8dce6594>] ? del_timer_sync+0x44/0x50
[  250.710482]  [<ffffffffc0b8de4e>] ? releaseGeneration+0x7e/0xa0 [kvdo]
[  250.710509]  [<ffffffffc0b8e018>] ? finishPageWrite+0x68/0x150 [kvdo]
[  250.710537]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  250.710543]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  250.710569]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  250.710574]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  250.710579]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  250.710583]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  250.710830] kvdo0:journalQ: 
[  250.710831] Error closing VDO
[  250.710833] : kvdo: The device is in read-only mode (2069)

[  250.710840] kvdo0:journalQ: 
[  250.710841] Error closing VDO
[  250.710842] : kvdo: The device is in read-only mode (2069)

[  250.711676] kvdo0:journalQ: 
[  250.711677] Error closing VDO
[  250.711678] : kvdo: The device is in read-only mode (2069)

[  250.752125] kvdo0:dmsetup: 
[  250.752127] device 'vdo0' stopped

[  274.427540] kvdo1:dmsetup: 
[  274.427541] starting device 'vdo1'

[  274.427558] kvdo1:dmsetup: 
[  274.427559] underlying device, REQ_FLUSH: supported, REQ_FUA: not supported

[  274.427562] kvdo1:dmsetup: 
[  274.427563] Using write policy async automatically.

[  274.427583] kvdo1:dmsetup: 
[  274.427584] zones: 1 logical, 1 physical, 1 hash; base threads: 5

[  274.538556] kvdo1:dmsetup: 
[  274.538558] Setting UDS index target state to online

[  274.538568] kvdo1:dmsetup: 
[  274.538569] device 'vdo1' started

[  274.538673] uds: kvdo1:dedupeQ: 
[  274.538675] creating index: dev=/dev/disk/by-id/ata-SAMSUNG_MZ7LM960HMJP-00005_S2TZNX0J402978 offset=4096 size=23847940096

[  274.538739] kvdo1:dmsetup: 
[  274.538740] resuming device 'vdo1'

[  274.538743] kvdo1:dmsetup: 
[  274.538744] device 'vdo1' resumed

[  274.539302] uds: kvdo1:dedupeQ: 
[  274.539304] Using 8 indexing zones for concurrency.

[  274.540120] uds: kvdo1:dedupeQ: 
[  274.540121] verifyBufferedData got unexpected data
[  274.540123] : UDS Error: Corrupt saved component (1030)

[  274.540129] uds: kvdo1:dedupeQ: 
[  274.540130] index_0: could not allocate index
[  274.540131] : UDS Error: Corrupt saved component (1030)

[  274.540213] uds: kvdo1:dedupeQ: 
[  274.540214] failed to create index
[  274.540214] : UDS Error: Corrupt saved component (1030)

[  274.540216] uds: kvdo1:dedupeQ: 
[  274.540217] Failed to make router
[  274.540218] : UDS Error: Corrupt saved component (1030)

[  274.540242] uds: kvdo1:dedupeQ: 
[  274.540242] Failed creating index
[  274.540243] : UDS Error: Corrupt saved component (1030)

[  274.540255] kvdo1:dedupeQ: 
[  274.540257] Error creating index dev=/dev/disk/by-id/ata-SAMSUNG_MZ7LM960HMJP-00005_S2TZNX0J402978 offset=4096 size=23847940096
[  274.540258] : UDS Error: Corrupt file (1030)

[  274.540260] kvdo1:dedupeQ: 
[  274.540260] Setting UDS index target state to error

[  274.566894] kvdo1:packerQ: 
[  274.566895] compression is enabled

[  284.121027] uds: kvdo1:journalQ: 
[  284.121028] assertion "
[  284.121031] DataVIOs released from recovery journal in order. Recovery journal point is (1, 0), but commit waiter point is (0, 1)
[  284.121033] " (beforeJournalPoint(&journal->commitPoint, &dataVIO->recoveryJournalPoint)) failed at /usr/local/src/kvdo-master/vdo/base/recoveryJournal.c:1078

[  284.121036] uds: kvdo1:journalQ: 
[  284.121037] [backtrace]

[  284.121042] CPU: 6 PID: 2444 Comm: kvdo1:journalQ Tainted: G        W  O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  284.121043] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  284.121046]  0000000000000000 ffffffff8df2f774 ffff9e9a0c0b7060 ffffc0c5c2cd3d40
[  284.121051]  ffffffffc0b53109 ffff9e9a00000030 ffffc0c5c2cd3d60 ffffc0c5c2cd3d10
[  284.121055]  2d25293f5b13c27e ffffffff8dce5494 00000000000126c0 ffffc0c5c2cd3da0
[  284.121059] Call Trace:
[  284.121068]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  284.121089]  [<ffffffffc0b53109>] ? assertionFailedLogOnly+0x49/0x70 [uds]
[  284.121094]  [<ffffffff8dce5494>] ? lock_timer_base+0x74/0x90
[  284.121121]  [<ffffffffc0ba11c1>] ? continueCommittedWaiter+0x91/0x130 [kvdo]
[  284.121140]  [<ffffffffc0ba1130>] ? continueWaiter+0x70/0x70 [kvdo]
[  284.121162]  [<ffffffffc0b9779f>] ? notifyNextWaiter+0x3f/0x70 [kvdo]
[  284.121180]  [<ffffffffc0b97834>] ? notifyAllWaiters+0x64/0x90 [kvdo]
[  284.121198]  [<ffffffffc0ba2300>] ? completeWrite+0xd0/0x630 [kvdo]
[  284.121217]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  284.121222]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  284.121239]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  284.121243]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  284.121246]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  284.121250]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  284.121294] uds: kvdo1:physQ0: 
[  284.121295] assertion "
[  284.121298] recovery journal point is monotonically increasing, recovery point: 0.1, block recovery point: 1.0
[  284.121300] " (beforeJournalPoint(&journal->recoveryPoint, recoveryPoint)) failed at /usr/local/src/kvdo-master/vdo/base/slabJournal.c:870

[  284.121303] uds: kvdo1:physQ0: 
[  284.121303] [backtrace]

[  284.121308] CPU: 1 PID: 2447 Comm: kvdo1:physQ0 Tainted: G        W  O    4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[  284.121309] Hardware name: Supermicro Super Server/X10SRM-TF, BIOS 2.0a 06/24/2016
[  284.121311]  0000000000000000 ffffffff8df2f774 0000000000010408 ffffc0c5c2cebd20
[  284.121316]  ffffffffc0b5309f ffff9e9a00000030 ffffc0c5c2cebd48 ffffc0c5c2cebce8
[  284.121320]  a44778a955fe7f07 a44778a955fe7f07 ffff9e9a2f21e000 ffff9e9a3fc58980
[  284.121324] Call Trace:
[  284.121331]  [<ffffffff8df2f774>] ? dump_stack+0x5c/0x78
[  284.121351]  [<ffffffffc0b5309f>] ? assertionFailed+0x4f/0x70 [uds]
[  284.121380]  [<ffffffffc0b90c90>] ? addEntry+0x70/0x170 [kvdo]
[  284.121400]  [<ffffffffc0b90f67>] ? addEntryFromWaiter+0x1d7/0x2a0 [kvdo]
[  284.121405]  [<ffffffff8e210edf>] ? schedule_timeout+0x16f/0x380
[  284.121428]  [<ffffffffc0b9779f>] ? notifyNextWaiter+0x3f/0x70 [kvdo]
[  284.121447]  [<ffffffffc0b901fa>] ? addEntries.part.8+0xda/0x280 [kvdo]
[  284.121469]  [<ffffffffc0ba92b6>] ? workQueueRunner+0x1a6/0x5f0 [kvdo]
[  284.121473]  [<ffffffff8dcbb050>] ? prepare_to_wait_event+0xf0/0xf0
[  284.121492]  [<ffffffffc0ba9110>] ? initKernelVDOOnce+0x20/0x20 [kvdo]
[  284.121496]  [<ffffffff8dc984c9>] ? kthread+0xd9/0xf0
[  284.121499]  [<ffffffff8dc983f0>] ? kthread_park+0x60/0x60
[  284.121502]  [<ffffffff8e2125f7>] ? ret_from_fork+0x57/0x70
[  284.121552] kvdo1:journalQ: 
[  284.121554] Unrecoverable error, entering read-only mode
[  284.121555] : UDS Internal Error: Assertion failed (66568)

**Comment by tomasz-grobelny** [comment]
Indeed, I get slightly different error messages but the point is valid - the device cannot be used :-(

**Comment by c0d3z3r0** [comment]
Try 4.17.0-0.bpo.1-amd64 from stretch-backports. Works perfectly for me :-)
