### ISSUE TITLE
Big problem on deleting big file on vdo. It will stop all io request

### ISSUE THREAD

**Issue by leonunix** [dm-vdo/kvdo#16]
I have a big problem

I use glusterfs over vdo on xfs in case.
my vdo version
Kernel module:
  Loaded: true
  Name: kvdo
  Version information:
    kvdo version: 6.2.0.219

In my case We have many big file over than 500G some is 1T or 2T.
if it be deleteing. Vdo will hang all of io reqeust. 
Some small file like 20g or 50g. if size over 100G. this problem will be very frequency.
I also set discard_limit to 100 from 1500
dedep is off in my place
only compression in on
this is come information on my system.I use iostat to record

your will see dev utils is 100% and it will hang all io request

iostats: dm-3 is vdo device
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.38    0.00   28.95    0.64    0.00   70.03

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00   218.00    0.00 15055.00     0.00 61152.00     8.12     0.54    0.04    0.00    0.04   0.03  49.00
sda               0.00   205.00    1.00 16104.00     8.00 65908.00     8.19     0.78    0.05    0.00    0.05   0.04  70.00
sdc               0.00     4.00    0.00  125.00     0.00   644.00    10.30     0.06    0.50    0.00    0.50   0.01   0.10
dm-0              0.00     0.00    0.00  129.00     0.00   644.00     9.98     0.06    0.50    0.00    0.50   0.01   0.10
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
bcache0           0.00     0.00    0.00 15980.00     0.00 61144.00     7.65     0.87    0.05    0.00    0.05   0.05  75.40
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     1.00    0.00    0.00    0.00   0.00 100.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.51    0.00   29.62    0.76    0.00   69.11

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00   193.00    0.00 15245.00     0.00 61764.00     8.10     0.53    0.03    0.00    0.03   0.03  49.90
sda               0.00   192.00    1.00 16268.00     4.00 66512.00     8.18     0.77    0.05    0.00    0.05   0.04  69.60
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
bcache0           0.00     0.00    0.00 16137.00     0.00 61756.00     7.65     0.88    0.05    0.00    0.05   0.05  74.60
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     1.00    0.00    0.00    0.00   0.00 100.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.39    0.00   28.35    0.64    0.00   70.62

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00   143.00    0.00 15014.00     0.00 60648.00     8.08     0.54    0.04    0.00    0.04   0.03  50.20
sda               0.00   142.00    1.00 15996.00     4.00 65224.00     8.16     0.74    0.05    0.00    0.05   0.04  67.30
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
bcache0           0.00     0.00    0.00 15830.00     0.00 60648.00     7.66     0.87    0.05    0.00    0.05   0.05  73.30
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     1.00    0.00    0.00    0.00   0.00 100.00

top info
Tasks: 1929 total,   2 running, 140 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.8 us, 17.0 sy,  0.0 ni, 71.7 id,  8.0 wa,  0.0 hi,  0.4 si,  0.0 st
KiB Mem : 13158505+total,  7327428 free, 10939488+used, 14862756 buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used.  8015328 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2144 root      20   0       0      0      0 S  19.8  0.0   3767:26 kvdo0:journalQ
 2150 root      20   0       0      0      0 S  15.8  0.0   4701:00 kvdo0:physQ0
18560 root      20   0 2429296  40120   9004 S  12.2  0.0   1585:55 glusterfsd
 2161 root      20   0       0      0      0 R  11.2  0.0   3579:51 kvdo0:cpuQ0
 2162 root      20   0       0      0      0 S  11.2  0.0   3572:51 kvdo0:cpuQ1
17807 root       0 -20       0      0      0 D  10.2  0.0 109:02.36 kworker/5:0H
 2146 root      20   0       0      0      0 S   7.6  0.0   1678:45 kvdo0:logQ0
 2147 root      20   0       0      0      0 S   7.3  0.0   1674:34 kvdo0:logQ1
 2148 root      20   0       0      0      0 S   7.3  0.0   1674:09 kvdo0:logQ2
 2149 root      20   0       0      0      0 S   7.3  0.0   1672:51 kvdo0:logQ3
18567 root      20   0 2369988  31936   9068 S   5.9  0.0 483:05.83 glusterfsd
 2145 root      20   0       0      0      0 S   4.0  0.0   1572:49 kvdo0:packerQ
 2151 root      20   0       0      0      0 S   4.0  0.0   1446:38 kvdo0:hashQ0
 2152 root      20   0       0      0      0 S   4.0  0.0   1442:42 kvdo0:hashQ1
 2156 root      20   0       0      0      0 S   2.6  0.0 798:50.26 kvdo0:bioQ0
 2157 root      20   0       0      0      0 S   2.6  0.0 779:48.42 kvdo0:bioQ1
 2158 root      20   0       0      0      0 S   2.6  0.0 778:43.52 kvdo0:bioQ2
 2159 root      20   0       0      0      0 S   2.6  0.0 776:37.81 kvdo0:bioQ3
 2160 root      20   0       0      0      0 S   2.6  0.0 974:01.15 kvdo0:ackQ

**Comment by corwin** [comment]
This is likely caused by the fact that discards can have very large latency, something we intend to address in the near future.

Sorry for the very long delay getting back to you. If this is still an active issue, please get back in touch.
