### ISSUE TITLE
How to reduce CPU utilization on journal thread?

### ISSUE THREAD

**Issue by HerlinCoder** [dm-vdo/kvdo#19]
It seems that journal can only works on only one thread.
When I using fio for performance test, the CPU utilization of `kvdo0:journalQ` is about 90% when storage device is NVMe SSD (using `top `to get this) and is about 50% on a SATA SSD. I'm afraid the journal could be the bottleneck of this configuration because of high CPU utilization. 
Is that influences performance actually and how to reduce CPU utilization on journal thread?

**Comment by bgurney-rh** [comment]
Yes, there are a few thread types that have only one thread, including the "journalQ" thread.

Write workloads will use an increasing amount of CPU time in the journalQ thread as throughput increases.  In that sense, the journalQ thread is a bottleneck of maximum write performance.

System processors with faster per-core performance will be able to allow the journalQ thread to process recovery journal entries faster, resulting in higher throughput.

Reads do not require a recovery journal entry, therefore reads are not limited by the journalQ thread.

Do you have the fio command (or config file) for the workload that you are using in your test?

**Comment by HerlinCoder** [comment]
> Yes, there are a few thread types that have only one thread, including the "journalQ" thread.
> 
> Write workloads will use an increasing amount of CPU time in the journalQ thread as throughput increases. In that sense, the journalQ thread is a bottleneck of maximum write performance.
> 
> System processors with faster per-core performance will be able to allow the journalQ thread to process recovery journal entries faster, resulting in higher throughput.
> 
> Reads do not require a recovery journal entry, therefore reads are not limited by the journalQ thread.
> 
> Do you have the fio command (or config file) for the workload that you are using in your test?

yes, fio command is here
`fio --rw=write --bs=64k --name=vdo --directory=/mnt/VDOVolume --ioengine=libaio --numjobs=16 --iodepth=1 --size=2g --end_fsync=1 --fsync_on_close=1 --fallocate=0 --group_reporting`

**Comment by corwin** [comment]
Sorry we've left this hanging for so long...

While it is true that the single journal thread can become the bottleneck in high throughput situations, it would be quite difficult to have multiple journal threads while still maintaining correctness.
We have explored some designs for doing so and have also done a number of experiments which showed that parallelizing the journal thread did not improve the throughput or latency of the VDO device.
