### ISSUE TITLE
Cannot compile kvdo dkms version 6.2.2.24 on Manjaro linux-5.4.8

### ISSUE THREAD

**Issue by geremi1** [dm-vdo/kvdo#28]
Hi, I tried installing vdo and kvdo on Manjaro with "yaourt vdo kvdo-dkms". All is installing fine, except the dkms modules. Here is the [make.log](https://github.com/dm-vdo/kvdo/files/4049658/make.log) file. It is a duplicate case value. Is there any way it could compile ?

**Comment by Eszartek** [comment]
As per https://aur.archlinux.org/packages/kvdo-dkms/ , you need to custom compile your kernel with  CONFIG_HZ=1000 or use linux-zen.

I installed linux-zen an then everything built and worked well.

**Comment by geremi1** [comment]
Thank you very much, it worked after compilation :)
