### ISSUE TITLE
Can I partition on a vdo volume

### ISSUE THREAD

**Issue by hedongzhang** [dm-vdo/kvdo#30]
I have a disk with a capacity of 8T, I use this disk create a 32T vdo volume, I want partition on this vdo volume, So Is there any problem with that?

**Comment by hedongzhang** [comment]
I find partition lost after system reboot unless use partprobe

**Comment by rhawalsh** [comment]
Hi @hedongzhang,

My experience is the same.  I can create partitions, but after a reboot they don't show up until running `sudo partprobe <vdo_volume>` manually.

While it is possible to partition a VDO device, I wouldn't recommend it for reasons like that.  It's not something that we test on top of a VDO device.  I would suggest using LVM instead, as that is tested pretty regularly has been reliably assembled upon reboot.

**Comment by hedongzhang** [comment]
Thank you  @rhawalsh ,
LVM is a good idea, but LVM will increase the complexity, I'm afraid it will affect performance. Therefore, I'm more worried about data loss or other problems after creating the partition. For me, running "partprobe" after reboot is not a problem.

**Comment by marcin-github** [comment]
I don't think that LVM add noticeably perfomance difference.

**Comment by rhawalsh** [comment]
Hi @hedongzhang,

I agree with @marcin-github.  The overhead of a basic LVM stack is not significant in our experience and testing.

Assuming all of the necessary operations to persist the data have been performed by the software, VDO should not be losing that data with partitions after a reboot.  I'm just not a big fan of having to run partprobe after a reboot.

**Comment by hedongzhang** [comment]
Hi @rhawalsh 
I find this issue you replied: [question about unsupported configuration](https://github.com/dm-vdo/vdo/issues/26). 
![image](https://user-images.githubusercontent.com/13121689/108481243-ec69fe00-72d2-11eb-8617-ae47ee47a66d.png)
If the partition is align, partition a VDO device is no problem?

**Comment by rhawalsh** [comment]
Hi @hedongzhang ,

We do not actively test partitioning on top of a VDO volume.  It *should* work, but given the lack of testing I can't say definitively that there would be no problem.  Assuming you're aligned properly, it is my impression that the the volume should operate fine.

If you do end up giving it a shot, please be sure to share your experience with us.

**Comment by hedongzhang** [comment]
Thank you @rhawalsh,
I will do some test and share any problem in the test

**Comment by hedongzhang** [comment]
@rhawalsh So far, all tests are normal, except for the need to pay attention to partition alignment
