### ISSUE TITLE
 Is '# -c <warn_pct>' right? I thought '# -c <crit_pct>' was right. 

### ISSUE THREAD

**Issue by kjy8901** [dm-vdo/kvdo#31]
Hello. corwin

I saw monitoring perl code.
Even though it is a comment, I feel like there is something wrong.

``` perl
31 # -c <warn_pct>: critical threshold equal to or greater than
32 #                <warn_pct> percent.
33 #
34 # -w <crit_pct>: warning threshold equal to or greater than
35 #                <crit_pct> percent.
```

Shouldn't 'warn_pct' be changed to 'crit_pct' in line 31
and Shouldn't 'crit_pct' be changed to 'warn_pct' in line 34

* monitor_check_vdostats_physicalSpace.pl
* monitor_check_vdostats_logicalSpace.pl
* monitor_check_vdostats_savingPercent.pl

All three files are the same.

**Comment by bgurney-rh** [comment]
I'm actually the one who wrote the "monitor_check" programs, and I agree, those should read as follows:

```
# -c <crit_pct>: critical threshold equal to or greater than
#                <warn_pct> percent.
#
# -w <warn_pct>: warning threshold equal to or less than
#                <crit_pct> percent.
```

I made one revision to your suggestion, because if the warning threshold is less than the critical threshold, the exit status should go directly to MONITOR_SERVICE_CRITICAL.  (Or at least it did, the last time I tested it.  I have more confidence in the program's logic than I do in its comments.)

**Comment by bgurney-rh** [comment]
I should say, "if the warning threshold is greater than the critical threshold, the exit status should go directly to MONITOR_SERVICE_CRITICAL."

**Comment by kjy8901** [comment]
> I'm actually the one who wrote the "monitor_check" programs, and I agree, those should read as follows:
> 
> ```
> # -c <crit_pct>: critical threshold equal to or greater than
> #                <warn_pct> percent.
> #
> # -w <warn_pct>: warning threshold equal to or less than
> #                <crit_pct> percent.
> ```
> 
> I made one revision to your suggestion, because if the warning threshold is less than the critical threshold, the exit status should go directly to MONITOR_SERVICE_CRITICAL. (Or at least it did, the last time I tested it. I have more confidence in the program's logic than I do in its comments.)

I asked a question in case I was misunderstanding.
Thank you. bgurney-rh
