### ISSUE TITLE
Is it possible for deduplication to have a block size other than 4096?

### ISSUE THREAD

**Issue by serjponomarev** [dm-vdo/kvdo#37]
Hello
I changed the block size for vdoestimator in the source code and it worked great.
Can this be done for kvdo in order to reduce the size of indexes and memory requirements, or would it be too difficult?

**Comment by corwin** [comment]
Changing the block size in kvdo is very difficult indeed. Furthermore, for most use cases, doing so would result either in poorer performance or poorer space savings. For a more detailed explanation, see https://github.com/dm-vdo/kvdo/issues/18.

What are you trying to change the size to and what are you trying to achieve? Perhaps we can suggest a better solution.
