### ISSUE TITLE
It is possible to support reflink syscall.

### ISSUE THREAD

**Issue by oiaohm** [dm-vdo/kvdo#39]
https://www.winehq.org/pipermail/wine-devel/2021-July/191267.html

This change here made me think.  ext4 does not support the reflink syscalls.   What vdo does by de-duplicating does save disc space yes but is CPU expensive doing the compares.   Lets say ext4 sitting on vdo result in the reflink syscalls being functional when the reflink syscalls were used you straight up know its a duplicate without having to perform a compare to find out. 

This would allow supporting user space de-duplication on demand.   So that a vdo with deduplication off does not have to be 100 percent without de-duplication.    I don't think there is a clean syscall for compress this file I could be wrong.

**Comment by corwin** [comment]
That is a great idea, but with the current structure of the kernel, it is not possible for VDO to do that. A reflink is a filesystem level construct, whereas VDO operates inside the block layer. Down at the level of VDO, there is no concept of a file, there are only blocks.
