### ISSUE TITLE
Where is the dm-vdo `dmsetup create foo --table ...` documentation?

### ISSUE THREAD

**Issue by ewheelerinc** [dm-vdo/kvdo#43]
Hello,

I would like to understand the low-level behavior of VDO at the target level.  Where is the vdo target's `dmsetup create` and `dmsetup message` documentation?

I've looked around, usually there is a `dm-<target>.txt` or similar document (like Documentation/device-mapper/cache.txt in the kernel tree) that defines all of the device-mapper table options, but I couldn't find anything informative when grepping these "vdo" and "kvdo" GIT trees for `dmsetup.*create` and the like.  

Is there such a document?  If not, where does kvdo parse the table arguments in your kernel module?

Thanks for your help!

-Eric

**Comment by sweettea** [comment]
Hi Eric; I apologize for the delay in replying, I was hoping that we could get the relevant documentation pushed to the unstable branch on Friday but it didn't happen; we should get this doc pushed there soon. In the meantime, here's our work-in-progress dm-vdo.rst documenting the table line.

https://gist.github.com/sweettea/2fbb5b4ddc92a7b30f6c38be78a7bd00

**Comment by ewheelerinc** [comment]
Awesome, thanks!  I'll let you close this in case you want it open until it pushes upstream.
