### ISSUE TITLE
Don't compile with 5.15.10-1.el8.elrepo.x86_64

### ISSUE THREAD

**Issue by slavonnet** [dm-vdo/kvdo#44]
many errors about builtin_va*
```
In file included from ./include/linux/kernel.h:5,
                 from /var/lib/dkms/kvdo/8.1.0.316/build/uds/stringUtils.h:26,
                 from /var/lib/dkms/kvdo/8.1.0.316/build/uds/common.h:25,
                 from /var/lib/dkms/kvdo/8.1.0.316/build/uds/buffer.h:25,
                 from /var/lib/dkms/kvdo/8.1.0.316/build/uds/indexLayout.h:25,
                 from /var/lib/dkms/kvdo/8.1.0.316/build/uds/indexLayout.c:22:
./include/linux/stdarg.h:6: ошибка: «va_start» переопределён [-Werror]
 #define va_start(v, l) __builtin_va_start(v, l)
```

and not have new enum switch
```
/var/lib/dkms/kvdo/8.1.0.316/build/vdo/dmvdo.c: В функции «vdo_status»:
/var/lib/dkms/kvdo/8.1.0.316/build/vdo/dmvdo.c:177:2: ошибка: в переключателе пропущено значение «STATUSTYPE_IMA» перечислимого типа [-Werror=switch]
  switch (status_type) {
  ^~~~~~
cc1: все предупреждения считаются ошибками
```

**Comment by sweettea** [comment]
Hi @slavonnet:

Unfortunately the newest stable release, 6.2.6.3, does not support such a new kernel on RHEL8, sadly. However, the unstable branch should be usable and not hit those compile errors: https://github.com/dm-vdo/kvdo/blob/unstable/ . Hope this helps!

**Comment by nyoxi** [comment]
Unfortunately the unstable branch does not work either as it still contains calls to `bvec_kmap_irq`/`bvec_kunmap_irq` which were removed in 4.15 in favor of `bvec_kmap_local`. See: https://lore.kernel.org/all/20210727055646.118787-1-hch@lst.de/

**Comment by nyoxi** [comment]
Actually the unstable branch builds fine. I didn't notice it has different code for newer kernels. Sadly the latest release 8.1.1.287 still fails on `stdarg.h`.

**Comment by rhawalsh** [comment]
Hi @nyoxi ,

Thanks for the updates.  I maintain a fork over at https://github.com/rhawalsh/kvdo and https://github.com/rhawalsh/vdo that is intended to work with the various Fedora releases and the latest mainline kernel (via Rawhide)...  I am working on doing the COPR builds for the latest code push.  Given what you're saying, it looks like you'll want to look at my fork (and maybe COPR repos) for a functional version against the current kernel versions.  I'll drop a post here once I have something operational.

**Comment by nyoxi** [comment]
No worries, I managed to get it working on my machine by replacing `#include <stdarg.h>` with `#include <linux/stdarg.h>`. Obviously a general fix will need to use something better (possibly a combination with `#if LINUX_VERSION_CODE < KERNEL_VERSION(5,15,0)` or something) to keep things working for both older and newer kernel.

No, I don't know if there's anything special in 5.15.10-1.el8.elrepo that is not in mainline. Also, I am building the module on ArchLinux and not on EL.
