### ISSUE TITLE
kvdo 6.1.3.23 hang operating system

### ISSUE THREAD

**Issue by qqshow** [dm-vdo/kvdo#46]
I create 3  vdo logical volumes as backup storage, after 50days running, my system is not responsiable hang， can't login by ssh.

My system's kernel is 3.10.0-957.
![image](https://user-images.githubusercontent.com/525425/155107300-d61678f4-e855-4c3b-ae95-8ef04822cba4.png)

Blow is the info from messages file,
![image](https://user-images.githubusercontent.com/525425/155106196-2f525a61-f6e5-4f66-abd0-c410329f6522.png)

After some repeated info, the last message info is
![image](https://user-images.githubusercontent.com/525425/155106559-2516bbfd-6990-4c6f-96de-dd3b99345e8a.png)

**Comment by raeburn** [comment]
Does the console scroll buffer show you any more info above the top of the screen snapshot shown above? I suppose it might be filled up by the time you get this...

Even if you can't log in, you might be able to collect a bit more data. If you've got SysRq keys enabled on your system, using Alt+SysRq+T should show what threads are active on the system, and Alt+SysRq+L should show a stack trace for whatever is running on each CPU, though from the looks of your console the journal daemon isn't keeping up very well. A few tries with each key combo (with a delay in between) might still log some useful information, with a bit of luck.

If you have crash dumps enabled on your system, Alt+SysRq+C should trigger one, and then the "crash" program can examine it and the debug info for your kernel and VDO modules and show you the process table and the stack traces for the active threads, so we can see what's going on.

**Comment by qqshow** [comment]
[vmcore-demsg.zip](https://github.com/dm-vdo/kvdo/files/8332293/vmcore-demsg.zip)
Here is vmcore-dmesg file from other
