### ISSUE TITLE
kvdo does not compile on Fedora 27

### ISSUE THREAD

**Issue by str8edgedave** [dm-vdo/kvdo#5]
I realize Fedora is not properly supported. I have tested on CentOS and everything works as expected.

My system is fully up-to-date using dnf.

    $ cat /etc/fedora-release
    Fedora release 27 (Twenty Seven)`

    $ rpm -q kernel kernel-core kernel-devel kernel-headers gcc
    kernel-4.14.14-300.fc27.x86_64
    kernel-core-4.14.14-300.fc27.x86_64
    kernel-devel-4.14.14-300.fc27.x86_64
    kernel-headers-4.14.14-300.fc27.x86_64
    gcc-7.2.1-2.fc27.x86_64`

    `$ uname -a
    Linux linux.local.lan 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Following the instructions:

    $ git clone https://github.com/dm-vdo/kvdo.git
    Cloning into 'kvdo'...
    remote: Counting objects: 573, done.
    remote: Total 573 (delta 0), reused 0 (delta 0), pack-reused 573
    Receiving objects: 100% (573/573), 1.06 MiB | 3.77 MiB/s, done.
    Resolving deltas: 100% (179/179), done.
    $ cd kvdo
    $ make -C /usr/src/kernels/`uname -r`/ M=`pwd`
    make: Entering directory '/usr/src/kernels/4.14.14-300.fc27.x86_64'
      AR      /home/user/devel/vdo/kvdo/uds/built-in.o
      CC [M]  /home/user/devel/vdo/kvdo/uds/stringLinuxKernel.o
      CC [M]  /home/user/devel/vdo/kvdo/uds/threadSemaphoreLinuxKernel.o
    /home/user/devel/vdo/kvdo/uds/threadSemaphoreLinuxKernel.c: In function ‘acquireSemaphore’:
    /home/user/devel/vdo/kvdo/uds/threadSemaphoreLinuxKernel.c:99:7: error: implicit declaration of function ‘__set_task_state’; did you mean ‘__get_task_state’? [-Werror=implicit-function-declaration]
           __set_task_state(task, TASK_INTERRUPTIBLE);
           ^~~~~~~~~~~~~~~~
           __get_task_state
    cc1: all warnings being treated as errors
    make[2]: *** [scripts/Makefile.build:315: /home/user/devel/vdo/kvdo/uds/threadSemaphoreLinuxKernel.o] Error 1
    make[1]: *** [scripts/Makefile.build:573: /home/user/devel/vdo/kvdo/uds] Error 2
    make: *** [Makefile:1511: _module_/home/user/devel/vdo/kvdo] Error 2
    make: Leaving directory '/usr/src/kernels/4.14.14-300.fc27.x86_64'

**Comment by JoelStienlet** [comment]
Hello!
I've had the same problem, 
replaced __set_task_state(task, TASK_INTERRUPTIBLE);
by __set_current_state(TASK_INTERRUPTIBLE);

and __GFP_REPEAT 
by __GFP_RETRY_MAYFAIL

but then it complains that ‘struct bio’ has no member named ‘bi_error’. I've no time to investigate that further. Apparently it needs some changes to compile.
Will this module be merged upstream someday? The kernel source changes so often that it takes a lot of work to maintain otherwise...

**Comment by rhawalsh** [comment]
We are working on implementing support for Fedora 27.  Longer-term, we are working on getting integrated upstream as mentioned in the README.md

**Comment by xsuchy** [comment]
I would like to see support for Fedor 27 as well. Thank you.

**Comment by serjponomarev** [comment]
When will the support for kvdo appear in Fedora 27? Month? Two month? Answer please.

**Comment by corwin** [comment]
I am pleased to announce that Fedora 27 support is now available!
