### ISSUE TITLE
Version 8.2.3.3 : changelog missing

### ISSUE THREAD

**Issue by tigerblue77** [dm-vdo/kvdo#68]
Hello,
is it possible to add a few lines as a changelog for v8.2.3.3 ? Thanks in advance

**Comment by lorelei-sakai** [comment]
I'm not quite sure what you mean here. Because of your comment, I noticed that I wrote the description for the release differently than in the past, so I fixed that. Is that what you were looking at, or is there something else that you'd like changed?

**Comment by tigerblue77** [comment]
Hello @lorelei-sakai, thanks for your edit, that's exactly the edit I was asking for ! Have a nice weekend :)
