### ISSUE TITLE
Upgrade of kmod-kvdo fails

### ISSUE THREAD

**Issue by xsuchy** [dm-vdo/kvdo#7]
I just tried to upgrade kmod-kvdo-6.1.1.12-1.fc27.x86_64 rpm package. And I got:

```
  Running scriptlet: kmod-kvdo-6.1.1.12-1.fc27.x86_64                                                         644/1005
modprobe: FATAL: Module kvdo is in use.
modprobe: FATAL: Module uds is in use.
error: executing %preun(kmod-kvdo-6.1.1.12-1.fc27.x86_64) scriptlet failed, return code: 1
Error in PREUN scriptlet in rpm package kmod-kvdo
Error in PREUN scriptlet in rpm package kmod-kvdo
```

**Comment by rhawalsh** [comment]
To make sure there are no compatibility problems between the userspace code and the kernel modules, we require that the modules are unloaded prior to upgrading or removing the kmod-kvdo package.  Please stop any running VDO volumes you have running, and the 'modprobe -r' operation should complete successfully.

**Comment by xsuchy** [comment]
When I check the script:

```
rpm -ql kmod-kvdo-6.1.1.12-1.fc27.$(arch) | grep '\.ko$' > /var/run/rpm-kmod-kvdo-modules
modprobe -r kvdo
modprobe -r uds
```
It is incorrect on several levels. 

1) Never ever, try calling rpm from scriptlet. RPM is not reentrant and this can cause a problem.

2) If you want to test if package is upgraded or removed you can test $0. See https://fedoraproject.org/wiki/Packaging:Scriptlets

3) You are using /var/run/ to save state between scriptlets. There are guidelines for that https://fedoraproject.org/wiki/Packaging:Scriptlets#Saving_state_between_scriptlets

The main problem is the modprobe -r -- I believe that it should be:

```
%preun
if [ $1 -eq 0 ] ; then
  # package removal
  modprobe -r kvdo
  modprobe -r uds
fi
```

**Comment by xsuchy** [comment]
Aha, then it would be better to fail with some nice error message. E.g.:

modprobe -r kvdo || echo "Error: kernel module kvdo is in use. Please stop all VDO volumes first and then continue."

**Comment by rhawalsh** [comment]
Thank you for the feedback.  It is a reasonable request, and I will look into implementing it.

**Comment by corwin** [comment]
We're now using DKMS so this issue is now moot.
