### ISSUE TITLE
KVDO Build Error on Fedora 40

### ISSUE THREAD

**Issue by glvxar** [dm-vdo/kvdo#87]
Since upgrade to fedora 40, kvdo is not working anymore. With new kernel 6.9.4 still with error on building.

**Module kvdo not found in directory /lib/modules/6.9.4-200.fc40.x86_64**

**Comment by glvxar** [comment]
Module need to be loaded manually.

Adding to /etc/modules-load.d/dm-vdo.conf solved load after reboot.

**Comment by lorelei-sakai** [comment]
I'm glad you figured this out. I somehow overlooked this issue, sorry for the late response.

As of kernel version 6.9.0, dm-vdo is included as a device-mapper target so the kvdo module should no longer be needed. But as you discovered, it is not enabled by default so you do have to make sure it enabled manually.
